_target_: src.models.klein_vae_module.KleinVAEModule

# KleinVAE hyperparameters
prior_mean: 0.5
prior_std: 0.1
lr: 0.01
kl_weight: ${kl_weight}

# Optimizer configuration
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: ${..lr}
  weight_decay: 0.0

# Scheduler configuration
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.99
  patience: 0

# SimpleVAE network configuration
model:
  _target_: src.models.components.vae.SimpleVAE
  input_dim: 900 # 30x30 for circles dataset
  hidden_dims: ${hidden_dims} #[1024, 512, 128, 32]
  latent_dim: 2

recon_loss:
  _target_: torch.nn.BCELoss
  reduction: mean
